SHOW DATABASES;

USE DATABASE CRUNCHBASE_BASIC_COMPANY_DATA;

SHOW SCHEMAS;

USE SCHEMA PUBLIC;

SHOW TABLES;

SHOW VIEWS;

SELECT * FROM ORGANIZATION_SUMMARY LIMIT 10;

SELECT COUNT(*) AS NUMBERS_ROW FROM ORGANIZATION_SUMMARY;

SELECT DISTINCT (uuid) FROM ORGANIZATION_SUMMARY;

SELECT DISTINCT (ROLES) FROM ORGANIZATION_SUMMARY;

SELECT CITY, COUNTRY_CODE, COUNT(COUNTRY_CODE) AS COUNTRY_COUNT
FROM ORGANIZATION_SUMMARY
GROUP BY COUNTRY_CODE
ORDER BY COUNTRY_COUNT DESC;


SELECT COUNTRY_CODE, COUNT(COUNTRY_CODE) AS COUNTRY_COUNT
FROM ORGANIZATION_SUMMARY
WHERE COUNTRY_CODE IS LIKE ('SWE','DNK','NOR','FIN','ISL')
GROUP BY CITY, COUNTRY_CODE
ORDER BY NUMBER_ORGANIZATIONS DESC;